name: test
'on':
- pull_request
jobs:
  testing:
    runs-on:
    - ubuntu-latest
    steps:
    - name: Run Tests
      env: 
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      run: echo $GITHUB_TOKEN
